"""
Natural-language ↔ SAP column/table hints derived from common reporting questions.
Used for table shortlisting, schema relevance scoring, and column alias enrichment.
Kept separate from schema_index.py for maintainability.
"""
from __future__ import annotations

from typing import Dict, List, Tuple

# table_name (any case) -> NL phrases helping match questions to whole tables
TABLE_NAME_NL_HINTS: Dict[str, List[str]] = {
    "VBRK": ["billing header", "invoice header", "billing document header", "sd billing header", "fi link billing"],
    "VBRP": ["billing line", "invoice line", "item revenue", "billing item", "sd item"],
    "VBAK": ["sales order header", "so header", "order header", "sd order"],
    "VBAP": ["sales order item", "so item", "order line", "sales item"],
    "VBEP": ["schedule line", "delivery schedule", "open quantity"],
    "LIKP": ["delivery header", "outbound delivery", "shipment header"],
    "LIPS": ["delivery item", "delivery line", "picked quantity", "gi line"],
    "EKKO": ["purchase order header", "po header", "purchasing document"],
    "EKPO": ["purchase order item", "po line", "po item", "procurement item"],
    "KNA1": ["customer master", "business partner customer", "sold-to master"],
    "KNVV": ["customer sales data", "sales area data customer"],
    "KNVP": ["customer partner", "partner function"],
    "LFA1": ["vendor master", "supplier master"],
    "MAKT": ["material description", "material text", "product name table"],
    "MARA": ["material master", "product master"],
    "MARC": ["material plant", "mrp area", "plant material"],
    "MARD": ["storage location stock", "stock quantity", "bin stock"],
    "MBEW": ["material valuation", "moving price", "standard price material"],
    "MCHB": ["batch stock", "batch quantity", "inventory batch"],
    "FAGLFLEXA": ["universal journal", "acfina", "gl actuals", "flexible ledger"],
    "BSEG": ["fi line item", "accounting line", "posting line"],
    "BKPF": ["fi document header", "accounting document header"],
    "BSAD": ["customer cleared items", "ar cleared", "cleared receivables"],
    "RBKP": ["invoice receipt", "logistics invoice", "miro header"],
    "RSEG": ["invoice receipt line", "miro item"],
    "KONV": ["pricing conditions", "sd pricing", "condition records"],
    "T016T": ["industry key text", "sector description"],
    "CEPC": ["profit center master", "pc master"],
    "CSKS": ["cost center master"],
    "COEP": ["co line items", "actual postings co"],
    "AUFK": ["order master", "internal order header"],
    "AFKO": ["pp order header", "production order header"],
    "AFPO": ["pp order item", "production order item"],
    "CKHS": ["costing header", "product costing header"],
    "CKIS": ["costing item", "cost component"],
    "CKIT": ["costing text", "cost element text"],
    "KEKO": ["product cost estimate", "costing run"],
    "CKMLHD": ["material ledger header", "ml header"],
    "CKMLCR": ["material ledger totals", "inventory value ml"],
    "MKPF": ["material document header", "goods movement header"],
    "RESB": ["reservation", "dependent requirement"],
    "STKO": ["bom header", "bill of material header"],
    "STPO": ["bom item", "bom component"],
    "DFKKOP": ["contract account document", "fi-ca document"],
    "sat_documents": ["cfdi", "mexico tax", "sat xml", "fiscal document"],
    "sat_canonical_merged": ["sat merge", "canonical sat", "merged cfdi"],
    "invoice_business_data": ["invoice analytics", "extracted invoice", "business invoice"],
    "invoice_v2_business_data": ["invoice v2", "validated pipeline"],
    "v2_validated_invoices": ["validated invoice json", "invoice validation"],
    "zodiac_invoice_success_edi": ["edi success", "converted invoice"],
    "zodiac_invoice_failed_edi": ["edi failure", "failed conversion"],
}

# column_name_lower -> phrases/substrings that often appear in user questions
SAP_COLUMN_NL_HINTS: Dict[str, List[str]] = {
    # Billing / sales (VBRK, VBRP, LIKP, LIPS)
    "netwr": [
        "net value",
        "net worth",
        "revenue",
        "sales value",
        "billing value",
        "invoice amount",
        "line value",
        "turnover",
        "sales amount",
        "order value",
        "po value",
        "purchase amount",
    ],
    "fkdat": ["billing date", "invoice date", "fkdat", "billing period", "posting date sales"],
    "fkimg": ["quantity billed", "billing qty", "invoiced quantity"],
    "waerk": ["currency", "document currency", "waerk"],
    "waers": ["currency", "local currency", "waers"],
    "vbeln": ["billing document", "invoice number", "document number", "vbeln", "delivery number"],
    "posnr": ["item", "line item", "position"],
    "matnr": ["material", "product", "sku", "item number", "matnr"],
    "arktx": ["material description", "product name", "description"],
    "maktx": ["material description", "product name", "description", "maktx"],
    "kunnr": ["customer", "sold-to", "payer", "account number", "kunnr"],
    "kunag": ["sold-to party", "customer", "buyer"],
    "kunrg": ["payer", "bill-to", "customer"],
    "vkorg": ["sales organization", "sales org"],
    "vtweg": ["distribution channel"],
    "spart": ["division", "product division"],
    "werks": ["plant", "factory", "site", "werks"],
    "lgort": ["storage location", "warehouse", "sloc"],
    "prctr": ["profit center", "pc", "prctr"],
    "kostl": ["cost center", "kostl"],
    "lfimg": ["delivery quantity", "delivered qty", "picked quantity"],
    "wadat": ["goods issue date", "delivery date", "loading date"],
    "land1": ["country", "nation", "land1"],
    "regio": ["region", "state", "province"],
    "brsch": ["industry", "sector", "business sector", "brsch"],
    "kdgrp": ["customer group", "key account group"],
    "gjahr": ["fiscal year", "year", "gjahr"],
    "poper": ["posting period", "period", "poper"],
    "fktyp": ["billing category", "billing type"],
    "fkart": ["billing type", "invoice type"],
    "mwsbk": ["tax", "vat", "sales tax"],
    "brtwr": ["gross value", "gross amount", "item gross", "gross order value"],
    "btgew": ["gross weight", "weight"],
    "ntgew": ["net weight"],
    "erdat": ["created on", "record date", "entry date"],
    "aedat": ["changed on", "last change date"],
    "erzet": ["entry time"],
    "vbtyp": ["document category", "sd document type"],
    "bstnk": ["customer po", "customer reference", "purchase order reference"],
    "inco1": ["incoterms", "delivery terms"],
    "charg": ["batch", "lot number", "batch number"],
    "charg_kunde": ["customer batch"],
    "bukrs": ["company code", "co code", "bukrs"],
    "rbukrs": ["company code", "ledger company"],
    "ryear": ["fiscal year", "ledger year", "ryear"],
    "runit": ["unit of measure ledger"],
    "rtcur": ["transaction currency", "tcurrency"],
    "drcrk": ["debit credit indicator", "debit credit"],
    "segment": ["segment reporting", "segment"],
    "cost_elem": ["cost element", "primary cost"],
    "rcntr": ["cost center", "rcntr"],
    "scntr": ["sender cost center"],
    "psegment": ["partner segment"],
    "kstar": ["cost element", "co cost element"],
    "kokrs": ["controlling area", "co area"],
    "rfarea": ["functional area"],
    "buzei": ["line number", "line item number"],
    "blart": ["document type", "fi document type"],
    "xblnr": ["reference", "reference document"],
    "zuonr": ["assignment", "assignment number"],
    "sgtxt": ["text", "item text", "line text"],
    "shkzg": ["debit credit", "s/h indicator"],
    "mwskz": ["tax code", "vat code"],
    "wmwst": ["tax amount"],
    "mwsts": ["tax amount local"],
    "zterm": ["payment terms", "terms of payment"],
    "zbd1t": ["cash discount days"],
    "inco2": ["incoterms location"],
    "lfbnr": ["document flow", "material doc reference"],
    "lfpos": ["mat doc item"],
    "bstme": ["order unit", "po unit"],
    "bprme": ["price unit", "order price unit"],
    "effwr": ["effective value"],
    "elikz": ["delivery completed", "closed indicator"],
    "erekz": ["final invoice", "invoice indicator"],
    "name1": ["name", "description name", "customer name", "vendor name"],
    "ort01": ["city", "town"],
    "pstlz": ["postal code", "zip"],
    "sortl": ["sort field", "search term"],
    "stceg": ["vat number", "tax id"],
    "ktokd": ["customer account group"],
    "ktokk": ["vendor account group"],
    "vkbur": ["sales office"],
    "vkgrp": ["sales group"],
    # Purchasing (EKKO, EKPO)
    "ebeln": ["purchase order", "po number", "order number", "ebeln"],
    "ebelp": ["po item", "order item"],
    "menge": ["quantity", "order quantity", "qty"],
    "netpr": ["unit price", "net price", "purchase price"],
    "bedat": ["order date", "po date", "purchase date"],
    "lifnr": ["vendor", "supplier", "creditor", "lifnr"],
    "ekorg": ["purchasing organization", "purchase org"],
    "ekgrp": ["buyer group", "purchasing group"],
    # FI / GL (BSEG, FAGLFLEXA, BSAD, RBKP)
    "dmbtr": ["amount", "value", "local currency amount", "dmbtr"],
    "wrbtr": ["amount document", "foreign currency", "wrbtr"],
    "hsl": ["amount", "ledger amount", "gl amount", "hsl"],
    "racct": ["gl account", "g/l account", "account number"],
    "belnr": ["document number", "fi document", "posting document"],
    "budat": ["posting date", "document date fi"],
    "bldat": ["document date", "invoice date fi"],
    "hkont": ["gl account", "general ledger"],
    "augdt": ["clearing date", "cleared on"],
    "rmwwr": ["invoice total", "gross amount", "vendor invoice amount"],
    "bewar": ["movement type", "transaction type"],
    "koart": ["account type", "vendor line", "customer line"],
    # Controlling / orders (AUFK, COEP, CSKS)
    "aufnr": ["order number", "internal order", "production order"],
    "ktext": ["order description", "order text"],
    "objnr": ["object number", "co object"],
    "wtgbtr": ["cost", "actual cost", "co amount"],
    "wkgbtr": ["co amount", "controlling amount"],
    # Materials (MARA, MARC, MBEW)
    "mtart": ["material type"],
    "matkl": ["material group"],
    "meins": ["unit of measure", "uom", "base unit"],
    "stprs": ["standard price", "std cost"],
    "verpr": ["moving average price"],
    "salk3": ["inventory value", "stock value"],
    "labst": ["stock", "on hand", "available stock"],
    # Costing (CKIS, CKHS, KEKO)
    "wertn": ["cost", "component value", "estimated cost"],
    "hwges": ["total cost", "cost estimate"],
    "kalnr": ["costing number", "cost estimate number"],
    # Industry text (T016T)
    "brtxt": ["industry description", "sector name"],
    # Pricing (KONV)
    "kbetr": ["condition rate", "discount amount", "price condition"],
    "kwert": ["condition value", "pricing value"],
    # SAT / app-style (invoice_business_data etc.)
    "total_amount": ["total", "invoice total", "amount"],
    "tax_amount": ["tax", "vat amount"],
    "invoice_date": ["invoice date", "billing date"],
    "customer_name": ["customer name", "client name"],
    "supplier_name": ["vendor name", "supplier name"],
    "fiscal_year": ["fiscal year", "financial year"],
}

# Phrase (substring in lowered question) -> (table, weight). Merged with schema_index defaults.
EXTRA_NL_PHRASE_TABLE_WEIGHTS: Dict[str, List[Tuple[str, float]]] = {
    "sales order": [("VBAK", 6.0), ("VBAP", 6.0), ("VBEP", 2.0)],
    "open order": [("VBAK", 4.0), ("VBAP", 5.0), ("VBEP", 4.0)],
    "backorder": [("VBAP", 4.0), ("VBEP", 5.0)],
    "stock": [("MARD", 5.0), ("MCHB", 3.0), ("LIPS", 2.5), ("MARC", 3.0)],
    "inventory": [("MARD", 5.0), ("MCHB", 3.5), ("MBEW", 4.0), ("CKMLCR", 2.5)],
    "movement": [("MKPF", 5.0), ("LSEG", 3.0), ("RESB", 3.0)],
    "goods movement": [("MKPF", 5.0), ("LSEG", 3.0)],
    "reservation": [("RESB", 6.0), ("MBEW", 2.0)],
    "gl account": [("BSEG", 5.0), ("FAGLFLEXA", 5.0)],
    "ledger": [("FAGLFLEXA", 6.0), ("BSEG", 4.0)],
    "posting": [("BSEG", 5.0), ("BKPF", 4.0), ("FAGLFLEXA", 4.0)],
    "accounts payable": [("BSEG", 5.0), ("LFA1", 3.0)],
    "accounts receivable": [("BSEG", 5.0), ("BSAD", 5.0), ("KNA1", 2.0)],
    "cleared": [("BSAD", 5.0), ("BSEG", 3.0)],
    "pricing": [("KONV", 6.0), ("VBRK", 3.0), ("EKKO", 2.0)],
    "discount": [("KONV", 5.0), ("VBRP", 2.0)],
    "bom": [("STKO", 5.0), ("STPO", 6.0), ("MAKT", 2.0)],
    "bill of material": [("STKO", 5.0), ("STPO", 6.0)],
    "routing": [("CRHD", 5.0), ("AFKO", 3.0)],
    "production order": [("AFKO", 5.0), ("AFPO", 5.0), ("AUFK", 4.0)],
    "cost estimate": [("CKHS", 5.0), ("CKIS", 5.0), ("KEKO", 4.0)],
    "standard cost": [("MBEW", 5.0), ("CKMLCR", 4.0)],
    "sat": [("sat_documents", 4.0), ("sat_canonical_merged", 3.0)],
    "cfdi": [("sat_documents", 5.0)],
    "invoice pipeline": [("invoice_business_data", 4.0), ("v2_validated_invoices", 3.0)],
    "validated invoice": [("v2_validated_invoices", 5.0), ("invoice_v2_business_data", 4.0)],
}
