"""
BridgeEDI Core — Invoice Processing Orchestrator (Phase 4).

Shared, country-neutral execution engine. Opt-in: a workspace runs on it only
when `workspace_settings.pipeline_enabled` is true, and no existing route calls
it. Importing this package has no side effects on production services.
"""
from .hooks import (
    AdapterResolver,
    AiEventSink,
    AuditSink,
    AuthenticationProvider,
    CollectingSink,
    ErpUpdater,
    LoggingAiEventSink,
    LoggingAuditSink,
    LoggingMonitoringSink,
    MonitoringSink,
    PlatformServices,
    PrincipalAuthenticator,
    RegistryAdapterResolver,
    WorkspaceContextResolver,
    WorkspaceResolver,
)
from .orchestrator import InvoicePipelineOrchestrator
from .retry import NO_RETRY, TRANSPORT_RETRY, RetryPolicy
from .stages import (
    STAGE_AI_EVENT,
    STAGE_AUTHENTICATE,
    STAGE_BUSINESS_RULES,
    STAGE_CONFIRMATION,
    STAGE_ERP_UPDATE,
    STAGE_FORMAT,
    STAGE_MAP,
    STAGE_MONITORING,
    STAGE_PARSE,
    STAGE_RESOLVE_ADAPTER,
    STAGE_RESOLVE_WORKSPACE,
    STAGE_SUBMIT,
    STAGE_TRANSFORM,
    STAGE_VALIDATE,
    StagePlan,
    StageSpec,
    adapter_stage,
    default_stage_plan,
)
from .types import (
    PipelineExecution,
    PipelineRequest,
    PipelineResult,
    PipelineStatus,
    StageFailed,
    StageOutcome,
    StageSkipped,
    StageStatus,
)

__all__ = [
    "InvoicePipelineOrchestrator",
    "PipelineRequest",
    "PipelineResult",
    "PipelineStatus",
    "PipelineExecution",
    "StageOutcome",
    "StageStatus",
    "StageFailed",
    "StageSkipped",
    "StagePlan",
    "StageSpec",
    "default_stage_plan",
    "adapter_stage",
    "PlatformServices",
    "AuthenticationProvider",
    "WorkspaceResolver",
    "AdapterResolver",
    "ErpUpdater",
    "MonitoringSink",
    "AiEventSink",
    "AuditSink",
    "PrincipalAuthenticator",
    "WorkspaceContextResolver",
    "RegistryAdapterResolver",
    "LoggingMonitoringSink",
    "LoggingAiEventSink",
    "LoggingAuditSink",
    "CollectingSink",
    "RetryPolicy",
    "NO_RETRY",
    "TRANSPORT_RETRY",
    "STAGE_AUTHENTICATE",
    "STAGE_RESOLVE_WORKSPACE",
    "STAGE_RESOLVE_ADAPTER",
    "STAGE_PARSE",
    "STAGE_VALIDATE",
    "STAGE_MAP",
    "STAGE_BUSINESS_RULES",
    "STAGE_TRANSFORM",
    "STAGE_FORMAT",
    "STAGE_SUBMIT",
    "STAGE_CONFIRMATION",
    "STAGE_ERP_UPDATE",
    "STAGE_MONITORING",
    "STAGE_AI_EVENT",
]
